# Name of the Spring Boot application
spring.application.name=ms-client-ui

# Logging level for the root logger
logging.level.root=INFO

# Port for the ms-client-ui microservice
server.port=8080

# Thymeleaf template engine configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Logging configuration for Feign clients
logging.level.feign=DEBUG
logging.level.com.openclassrooms.msclientui.proxy.FeignNote=DEBUG

# Feign client security configuration
feign.client.username=${CLIENT-UI_USERNAME}
feign.client.password=${CLIENT-UI_PASSWORD}