# Name of the Spring Boot application
spring.application.name=ms-gateway-server

# Port for the ms-gateway-server microservice
server.port=8082

# Logging level for the root logger
logging.level.root=INFO

#spring.application.admin.enabled=false

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

# Endpoint management settings
management.endpoints.web.exposure.include=health,info
management.endpoints.web.exposure.exclude=metrics,threaddump

# Spring cloud settings
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false
spring.cloud.discovery.locator.enabled=true
spring.cloud.discovery.locator.lower-case-service-id=true


# Security credentials for the application
security.username=${GATEWAY_USERNAME}
security.password=${GATEWAY_PASSWORD}