services:

  ########################################
  ##### Eureka-server
  ########################################
  ms-eureka-server:
    image: ms-eureka-server:latest
    build:
      context: ./ms-eureka-server
      dockerfile: dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - medilabo-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 30s   # Checks every 30 seconds
      timeout: 5s     # Waiting time for a response
      retries: 3      # Attempts before declaring the container 'unhealthy'
      start_period: 60s # Delay before starting the tests, to allow the service to stabilize

  ########################################
  ##### MySQL
  ########################################
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    depends_on:
      ms-eureka-server:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./ms-patient/src/main/resources/schemaMedilaboPatient.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "${APP_DB_HOST}", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 30s   # Checks every 30 seconds
      timeout: 5s     # Waiting time for a response
      retries: 3      # Attempts before declaring the container 'unhealthy'
      start_period: 60s # Delay before starting the tests, to allow the service to stabilize
    networks:
      - medilabo-network

  ########################################
  ##### MongoDB
  ########################################
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - ./ms-note/src/main/resources/medicalNotes.csv:/data/medicalNotes.csv
    command: >
      sh -c "
      mongod --bind_ip_all &
      sleep 5 &&
      mongoimport --host localhost --db medilabopatient --collection doctornotes --type csv --file ./data/medicalNotes.csv --headerline &&
      tail -f /dev/null
      "
    networks:
      - medilabo-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({ ping: 1 })' | mongosh --quiet"]
      interval: 30s   # Checks every 30 seconds
      timeout: 5s     # Waiting time for a response
      retries: 3      # Attempts before declaring the container 'unhealthy'
      start_period: 60s # Delay before starting the tests, to allow the service to stabilize

  ########################################
  ##### MS-Gateway-Server
  ########################################
  ms-gateway-server:
    image: ms-gateway-server:latest
    build:
      context: ./ms-gateway-server
      dockerfile: dockerfile
    container_name: ms-gateway-server
    ports:
      - "8082:8082"
    depends_on:
      mongo-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      GATEWAY_USERNAME: ${GATEWAY_USERNAME}
      GATEWAY_PASSWORD: ${GATEWAY_PASSWORD}
    networks:
      - medilabo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "${GATEWAY_USERNAME}:${GATEWAY_PASSWORD}", "http://localhost:8082/actuator/health"]
      interval: 30s   # Checks every 30 seconds
      timeout: 5s     # Waiting time for a response
      retries: 3      # Attempts before declaring the container 'unhealthy'
      start_period: 60s # Delay before starting the tests, to allow the service to stabilize

  ########################################
  ##### MS-Patient
  ########################################
  ms-patient:
    image: ms-patient:latest
    build:
      context: ./ms-patient
    container_name: ms-patient
    ports:
      - "8081:8081"
    depends_on:
      ms-gateway-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      APP_DB_HOST: ${APP_DB_HOST}
      APP_DB_PORT: ${APP_DB_PORT}
      APP_DB_NAME: ${APP_DB_NAME}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      PATIENT_USERNAME: ${PATIENT_USERNAME}
      PATIENT_PASSWORD: ${PATIENT_PASSWORD}
    networks:
      - medilabo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "${PATIENT_USERNAME}:${PATIENT_PASSWORD}", "http://localhost:8081/actuator/health"]
      interval: 30s   # Checks every 30 seconds
      timeout: 5s     # Waiting time for a response
      retries: 3      # Attempts before declaring the container 'unhealthy'
      start_period: 60s # Delay before starting the tests, to allow the service to stabilize

  ########################################
  ##### MS-Note
  ########################################
  ms-note:
    image: ms-note:latest
    build:
      context: ./ms-note
      dockerfile: dockerfile
    container_name: ms-note
    ports:
      - "8083:8083"
    depends_on:
      ms-patient:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      NOTE_USERNAME: ${NOTE_USERNAME}
      NOTE_PASSWORD: ${NOTE_PASSWORD}
      MSNOTE-FEIGN_USERNAME: ${MSNOTE_FEIGN_USERNAME}
      MSNOTE-FEIGN_PASSWORD: ${MSNOTE_FEIGN_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: ${MONGO_DATABASE}
    networks:
      - medilabo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "${NOTE_USERNAME}:${NOTE_PASSWORD}", "http://localhost:8083/actuator/health"]
      interval: 30s   # Checks every 30 seconds
      timeout: 5s     # Waiting time for a response
      retries: 3      # Attempts before declaring the container 'unhealthy'
      start_period: 60s # Delay before starting the tests, to allow the service to stabilize

  ########################################
  ##### MS-Diabete
  ########################################
  ms-diabete:
    image: ms-diabete:latest
    build:
      context: ./ms-diabete
      dockerfile: dockerfile
    container_name: ms-diabete
    ports:
      - "8084:8084"
    depends_on:
      ms-note:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      DIABETE_USERNAME: ${DIABETE_USERNAME}
      DIABETE_PASSWORD: ${DIABETE_PASSWORD}
      MSDIABETE-FEIGN_USERNAME: ${MSDIABETE_FEIGN_USERNAME}
      MSDIABETE-FEIGN_PASSWORD: ${MSDIABETE_FEIGN_PASSWORD}
      FEIGN_USERNAME: ${FEIGN_USERNAME}
      FEIGN_PASSWORD: ${FEIGN_PASSWORD}
    networks:
      - medilabo-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "-u", "${DIABETE_USERNAME}:${DIABETE_PASSWORD}", "http://localhost:8084/actuator/health" ]
      interval: 30s   # Checks every 30 seconds
      timeout: 5s     # Waiting time for a response
      retries: 3      # Attempts before declaring the container 'unhealthy'
      start_period: 60s # Delay before starting the tests, to allow the service to stabilize

  ########################################
  ##### MS-Client-UI
  ########################################
  ms-client-ui:
    image: ms-client-ui:latest
    build:
      context: ./ms-client-ui
      dockerfile: dockerfile
    container_name: ms-client-ui
    ports:
      - "8080:8080"
    depends_on:
      ms-diabete:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      CLIENT-UI_USERNAME: ${CLIENT_UI_USERNAME}
      CLIENT-UI_PASSWORD: ${CLIENT_UI_PASSWORD}
    networks:
      - medilabo-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "-u", "${CLIENT_UI_USERNAME}:${CLIENT_UI_PASSWORD}", "http://localhost:8080/actuator/health" ]
      interval: 30s   # Checks every 30 seconds
      timeout: 5s     # Waiting time for a response
      retries: 3      # Attempts before declaring the container 'unhealthy'
      start_period: 60s # Delay before starting the tests, to allow the service to stabilize

########################################
##### Networks
########################################
networks:
  medilabo-network:
    driver: bridge