# Build the Java application
FROM maven:3.9.9-eclipse-temurin-17-alpine AS build

# Set the working directory
WORKDIR /app

# Copy project files into the container
COPY pom.xml ./
COPY src ./src

# Compile and package the application (generates a JAR file in the target/ directory)
RUN mvn clean package -DskipTests && \
    rm -rf ~/.m2/repository

# Run the Java application
FROM eclipse-temurin:17-jre-alpine

# Add curl for the healthcheck
RUN apk add --no-cache curl

# Set the working directory
WORKDIR /app

# Copy the JAR file generated in the build stage
COPY --from=build /app/target/*.jar ms-eureka-server-1.0.0-SNAPSHOT.jar

# Expose the port used by the application
EXPOSE 8761

# Command to run the application
CMD ["java", "-jar", "ms-eureka-server-1.0.0-SNAPSHOT.jar"]