spring.application.name=ms-note
logging.level.root=INFO

# Port for the ms-note microservice
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=true