spring.application.name=ms-note
logging.level.root=INFO

# Port for the ms-note microservice
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=true

security.username=${NOTE_USERNAME}
security.password=${NOTE_PASSWORD}

#TODO à mettre en variable d'environnement
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=note