# Name of the Spring Boot application
spring.application.name=ms-diabete

# Logging level for the root logger
logging.level.root=INFO

# Port for the ms-diabete microservice
server.port=8084

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=true

# Endpoint management settings
management.endpoints.web.exposure.include=health,info
management.endpoints.web.exposure.exclude=metrics,threaddump

# Security credentials for the application
security.username=${DIABETE_USERNAME}
security.password=${DIABETE_PASSWORD}

# Logging configuration for Feign clients
logging.level.feign=INFO

# Feign client configuration
feign.note.username=${MSDIABETE-FEIGN_USERNAME}
feign.note.password=${MSDIABETE-FEIGN_PASSWORD}

# Sets the base URL for the ms-gateway service
feign.client.ms-gateway.url=http://localhost:8082