# Step1: Build the Java application
FROM maven:3.9.9-eclipse-temurin-17 AS build

# Set the working directory
WORKDIR /app

# Copy project files into the container
COPY pom.xml ./
COPY src ./src

# Compile and package the application (generates a JAR file in the target/ directory)
RUN mvn clean package -DskipTests

# Step 2: Run the Java application
FROM eclipse-temurin:17-jdk

# Set the working directory
WORKDIR /app

# Copy the JAR file generated in the build stage
COPY --from=build /app/target/*.jar ms-diabete-1.0.0-SNAPSHOT.jar

# Expose the port used by the application
EXPOSE 8084

# Command to run the application
CMD ["java", "-jar", "ms-diabete-1.0.0-SNAPSHOT.jar"]